### ISSUE TITLE
Three Broken Links

### ISSUE THREAD

**Issue by bh2smith** [gnosis/safe-docs#110]
The Safe App tutorial found at https://docs.gnosis.io/safe/docs/sdks_safe_apps/ contains a list of links to existing safe apps. Two of which (as far as I can tell) are broken.

- Compound:
     https://github.com/gnosis/safe-react-apps/tree/development/src/apps/Compound
     https://github.com/gnosis/safe-react-apps/tree/development/apps/compound

- Transaction Builder
     https://github.com/gnosis/safe-react-apps/tree/development/src/apps/TxBuilder
     https://github.com/gnosis/safe-react-apps/tree/development/apps/tx-builder

- Aave
     https://github.com/mrdavey/gnosis-safe-app
     Does not seem to exist on @mrdavey's github anywhere.

Also, perhaps this would be a good place to update the list to include [Wallet Connect](https://github.com/gnosis/safe-react-apps/tree/development/apps/wallet-connect)

**Comment by mrdavey** [comment]
Hey thanks for noticing! The Aave app is currently a private repo located at https://github.com/aave/gnosis-safe-app. Just waiting for Gnosis to update the SDK so I don't have to reveal infura keys to the world.
