### ISSUE TITLE
Confusion about docs/tutorial_tx_service_initiate_sign

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-docs#126]
A user pointed out that the phrasing is misleading in: `docs/tutorial_tx_service_initiate_sign`

>   "signature": "<0x prefixed hex string>",  // One or more ethereum ECDSA signatures of the `contractTransactionHash` as an hex string

It wasn't clear how multiple signatures need to be formatted as arrays are not accepted.

We could rephrase the comment to:
>   "signature": "<0x prefixed hex string>",  // One or more ethereum ECDSA signatures of the `contractTransactionHash` as an hex string. See: [signature types]( https://docs.gnosis.io/safe/docs/contracts_signatures/))

**Comment by Uxio0** [comment]
Multiple signatures are allowed but example is not documented. To send multiple signatures the should be appended and the hex string should be 0x prefixed, so for 2 signatures `0x1234` and `0x5678` the string that should be sent to the service should be `0x12345678`

**Comment by biafra23** [comment]
I think we just need to add a link to https://docs.gnosis.io/safe/docs/contracts_signatures/ to the comment. This page even has examples :-)
