### ISSUE TITLE
Add a doc explaining how to use custom TXs to interact with contracts for safe web client

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-docs#26]
Recently we got a fair amount of questions asking on how to use this feature. 

A doc for QA on how to test custom TXs which may help: https://docs.google.com/document/d/1z3WGxMvycNzJGKvWSVaMhoZaLcwKlDjD5rE_PvKPfYs/edit?usp=sharing

**Comment by jpalvarezl** [comment]
https://github.com/gnosis/safe-transaction-service-example

**Comment by rmeissner** [comment]
I don't think this belongs in the docs as these are for developers and not for our QA test plans 🤔 I would close the issue for now. We do have some material on how to directly interact with the services. We also have some help center articles on contract interaction
