### ISSUE TITLE
Incorrect field in EIP-712 signature specified

### ISSUE THREAD

**Issue by frostiq** [gnosis/safe-docs#63]
I think I found a mistake in the docs:
https://docs.gnosis.io/safe/docs/contracts_tx_execution/

The doc says that it’s needed to include “dataGas” field in EIP-712 signature
However, the smart contract expects “baseGas” field instead:
https://github.com/gnosis/safe-contracts/blob/master/contracts/GnosisSafe.sol#L370
And it considers signatures with dataGas as invalid

**Comment by rmeissner** [comment]
Yes this is correct, for the first version of the contract (pre 1.0.0) it was `dataGas`. We need to update this
