### ISSUE TITLE
Remove hardcoded paths

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-docs#68]
In multiple places asset paths are hardcoded (e.g. fonts, images) this cause them not to work properly (e.g. in staging).

Production works by "accident" since the required files have been deployed to root at some point before the sub directory change.

See https://github.com/gnosis/dex-docs/commit/8f8b04d24ca6d91350be85559dfaf7160faffc2c

**Comment by tschubotz** [comment]
https://github.com/gnosis/conditional-tokens-docs/commit/3e74890604697dee6c1d0b31c200fba06173df10
https://github.com/gnosis/conditional-tokens-docs/commit/0c265f951b72cdac2ba2309bfc84f47000cd9b55
